alias raspi-ssh='ssh alessio@192.168.1.13'
alias vik-api='sudo mount -av && cursor /mnt/raspi/vikschool-api && exit'
alias leadsystem='cursor /home/alessio/Documents/lavoro/otacon-funnel/leadsystem-comparacorsi && exit'
alias fix-wifi='sudo resolvectl dns wlan0 1.1.1.1 8.8.8.8'
alias fix-audio='systemctl --user restart pipewire wireplumber pipewire-pulse'
alias activate-airplane-mode='sudo rfkill block all'
alias deactivate-airplane-mode='sudo rfkill unblock all'
